---
title: "R Notebook"
output: html_notebook
---
```{r}
install.packages("lubridate")
library(lubridate) 



```

```{r}
df_bir <- data.frame( yas = c(10,11,30),
                      boy = c(120, 140, 160),
                      dogum = c("20100201","20110522","20090430")
                      )


df_iki <- data.frame( yas = c(10,11,30),
                      boy = c(120, 140, 160),
                      dogum = c("2010_02_01","2011_05_22","2009_04_30")
                      )


df_uc <- data.frame( yas = c(10,11,30),
                      boy = c(120, 140, 160),
                      dogum = c("01022010","22052011","30042009")
                      )


str(df_bir)
#dogum ifadesi character : date yapıcaz



ymd("20110522") #year month day
dmy("22031999")  # "1999-03-22" boyle formatlıyor
mdy("01011999") #mdy dmy ydm dersem bunlar icine  formatını nasıl gireceğim anlasılır



```
```{r}
dmy(df_uc$dogum)

```
```{r}
df_iki$dogum <- ymd(df_iki$dogum) 
df_iki
str(df_iki)
# $ boy  : num  120 140 160
 #$ dogum: Date, format:  ...
```











